#!/bin/bash

script_name=`basename ${0}`

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/install_gum"

ACTION=$(gum choose "create" "delete" "manage")

case "${ACTION}" in
  create) create_lxc_container "$@" ;;
  delete) lxc_delete ;;
  manage) lxc_manage ;;
   *) echo "Unknown option" ;;
esac
