#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/install_gum"

CONTAINER_NAME=`lxc_select_container`
gum spin -s line -a right --title "Deleting container..." -- lxc delete -f ${CONTAINER_NAME}
